name: photofeast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_slidable: ^3.1.0
  go_router: ^14.2.0
  google_generative_ai: ^0.4.3
  image_picker: ^1.1.2
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
