// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnVWnnw4wUEMoVJ4TMqhrjr1GpDmYufKs',
    appId: '1:202689525822:web:affd36b156e3dfb283396f',
    messagingSenderId: '202689525822',
    projectId: 'photofeast-1',
    authDomain: 'photofeast-1.firebaseapp.com',
    storageBucket: 'photofeast-1.appspot.com',
    measurementId: 'G-13H4M7CXNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-iW1j-dEbaZ1VbPWGZc66E-ISvOShcrw',
    appId: '1:202689525822:android:5e3d04e787612fd783396f',
    messagingSenderId: '202689525822',
    projectId: 'photofeast-1',
    storageBucket: 'photofeast-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL9JzPiNE7heAFTDzOMBbQmFFxfoVcbns',
    appId: '1:202689525822:ios:960df340f9130e9883396f',
    messagingSenderId: '202689525822',
    projectId: 'photofeast-1',
    storageBucket: 'photofeast-1.appspot.com',
    androidClientId: '202689525822-cqe7rvarubc0cc0bp3bg8b532kjbpafc.apps.googleusercontent.com',
    iosClientId: '202689525822-0m0kkli0atp8hk1l7392gfv9qdf01s17.apps.googleusercontent.com',
    iosBundleId: 'com.example.photofeast',
  );

}